apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: centaurwealth.dev
      http:
        paths:
          - path: /api/auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/auth/google/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-google-srv
                port:
                  number: 3000
          - path: /api/balance/?(.*)
            pathType: Prefix
            backend:
              service:
                name: balance-srv
                port:
                  number: 3000
          - path: /api/budget/?(.*)
            pathType: Prefix
            backend:
              service:
                name: budget-srv
                port:
                  number: 3000
          - path: /api/timeline/?(.*)
            pathType: Prefix
            backend:
              service:
                name: timeline-srv
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: ledger-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
