apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance
  template:
    metadata:
      labels:
        app: balance
    spec:
      containers:
        - name: balance
          image: shawlu95/centaur-balance
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'centaurwealth'
            - name: MONGO_DB
              value: 'balance'
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-pass
                  key: mongo_pass
            - name: jwt
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
---
apiVersion: v1
kind: Service
metadata:
  name: balance-srv
spec:
  selector:
    app: balance
  ports:
    - name: balance
      protocol: TCP
      port: 3000
      targetPort: 3000
