name: tests-balance

on:
  pull_request:
    paths:
      - 'balance/**'

jobs:
  build:
    # start up a container
    runs-on: ubuntu-latest
    steps:
      # take all codes in thie proj
      - uses: actions/checkout@v2
      - run: cd balance && npm install && npm run test:ci
